### ISSUE TITLE
Issue Using With Broserify

### ISSUE THREAD

**Issue by stevepop** [james2doyle/vue-ajax-form-component#2]
Thanks for this component, it is a solution to an issue I am facing with using Vuejs. However, I am trying to use this component in my Laravel application using Browserify.  Unfortunately I keep getting the following errors in console;
*\* Unknown custom element: <ajax-form> - did you register the component correctly? **
*\* Uncaught ReferenceError: Vue is not defined **

This is my app.js;

```
var Vue = require('vue');
Vue.use(require('vue-resource'));

import Blog from './components/Blog.vue';
new Vue({
    el: '#blog-posts',
    components: { Blog }
});
```

My gulpfile extract;

```
var elixir = require('laravel-elixir');
require('laravel-elixir-vueify');
elixir(function(mix) {
   // mix.phpUnit();
 mix.browserify("app.js");
.scripts([
        "resources/assets/js/frontend/vue.ajax-form.js"
], 'public/js/frontend.js', './');
```

I also tried to adding the vue.ajax-form.js directly in my html but still got the same error above.

I am not sure why the component is unable to get the Vue instance.

**Comment by james2doyle** [comment]
Could this be because there is no AMD or Common Js support in this component?

**Comment by stevepop** [comment]
Hi James, it is possible. I have now given up on the idea of using a custom component for now and have now directly referenced Vue, Vue-resource directly in the page where I need the form and I no longer have the error.
