### ISSUE TITLE
Can the component prevent repeated submission？

### ISSUE THREAD

**Issue by zwl1619** [james2doyle/vue-ajax-form-component#3]
Can the component prevent repeated submission？

**Comment by james2doyle** [comment]
You could hook into the `onFormComplete` event and remove the form or block the submission.

You can [see here](https://github.com/james2doyle/vue-ajax-form-component/blob/master/example.html#L71-L76) that there is an event for knowing when everything is done. So you could maybe set a boolean for `theFormHasBeenSubmitted` when this even is fired. Then, [at this event](https://github.com/james2doyle/vue-ajax-form-component/blob/master/example.html#L63-L66) check to see if the form has already been submitted or not.

There are probably server-side ways to do this, but that is very subjective.
